### ISSUE TITLE
ドメイン

### ISSUE THREAD

**Issue by takeyari** [AtamaAraiOtaku/AtamaAraiOtaku#2]
ドメインを取ろうと思うけどどれがいいですか
![](https://i.gyazo.com/f8528e6a7ead592695cb433a69b7fd32.png)

**Comment by takeyari** [comment]
他の種類のでも可

**Comment by book000** [comment]
gumma.jp

**Comment by xReiju** [comment]
頭洗いオタクソリューションズ

**Comment by Petitsurume** [comment]
.org

**Comment by takeyari** [comment]
まとまらなさそうだし候補出してくじ引きしますよ

**Comment by Petitsurume** [comment]
http://atama.araiotaku.xyz/
になりました。
